### ISSUE TITLE
Error resulting in Exit Code 2 when TIS-Advanced is installed

### ISSUE THREAD

**Issue by ThePatmann** [SamsTheNerd/HexGloop#17]
Crash Log:
https://gnomebot.dev/paste/1146223848417656842

Mod List:
https://gnomebot.dev/paste/1146227228665974874

I have tested this modpack with and without each mod, the error only occurs when both TIS-Advanced and HexGloop are installed.

The error log claims that I am missing dependencies which are in fact present in the mods folder. I do not know the cause, but  I assume since your mod is the only one added and that it ran prior to this addition that the issue might be present in your code. On the off chance that this is in error, I will also be posting a sister-issue on the TIS-Advanced mod.

**Comment by SamsTheNerd** [comment]
Looks like they're using an older version of mixin extras, seems like it was resolved here <https://gitlab.com/zack-emmert/tis-advanced/-/issues/2> but hasn't been pushed yet. you may be able to manually edit something in their jar or something to get it to work but you'd have to ask them about that
