### ISSUE TITLE
Fabric Dependency Decleration

### ISSUE THREAD

**Issue by JohnDog3112** [SamsTheNerd/HexGloop#2]
It seems like hex gloop doesn't properly tell fabric that it depends on wnboi, as when it crashes it gives a misleading crash report about hextweaks being the cause of the crash (with the missing wnboi class showing up further down).
[crash-2023-08-03_17.27.09-client.txt](https://github.com/SamsTheNerd/HexGloop/files/12256137/crash-2023-08-03_17.27.09-client.txt)

**Comment by SamsTheNerd** [comment]
fixed in 0.0.3
