### ISSUE TITLE
The Gloop Dupe

### ISSUE THREAD

**Issue by ZeekDaGeek** [SamsTheNerd/HexGloop#22]
It appears that there was an attempt to make it so the Gloop Dye could dye a whole stack of items at once, however, it instead allows you to dupe anything that can be dyed and stacked

Crafting something like this will give you 64 ducks in the hand, and leave 63 items in the crafting grid.
![image](https://github.com/SamsTheNerd/HexGloop/assets/1709288/68c68d25-77a3-4d51-a13d-fb5e270afd8d)

vs

Vanilla dying looks like this:
![image](https://github.com/SamsTheNerd/HexGloop/assets/1709288/3a8810ee-d2e3-4716-9275-ca3a06a2e594)

**Comment by SamsTheNerd** [comment]
ah, good to know. that's just from the crafting returning a `.copy()`of the original and forgetting to change the count of it, oops. Fixed for next update.

**Comment by SamsTheNerd** [comment]
Fixed in v0.1.0 !
