### ISSUE TITLE
Torty Transfer doesn't seem to respect destination slot when picking up an item entity

### ISSUE THREAD

**Issue by beholderface** [SamsTheNerd/HexGloop#26]
This hex works to teleport you and protect your items from getting tossed, but it doesn't restore the items to the slots they were in pre-cast, instead behaving as if picking them up naturally. The hex definitely knows which slot they're supposed to go in, and it's definitely picking them up (as opposed to picking them up naturally), it's just not doing it as expected.

[Teletort.txt](https://github.com/SamsTheNerd/HexGloop/files/13402674/Teletort.txt)

**Comment by SamsTheNerd** [comment]
(I think we discovered on discord that the hex was just picking up the air stack entities)
