### ISSUE TITLE
Don't dequeue patterns in Riutalist's Inscriber (SlateLoader)?

### ISSUE THREAD

**Issue by slava110** [SamsTheNerd/HexGloop#28]
Riutalist's inscriber is a nice tool to build **exactly one** spell circle. But if it can hold up to 64 slates maybe it makes sense to make it repeat patterns instead of removing them from the queue? This way player will be able to build multiple same spell circles if needed using this tool.
Maybe some visual or sound indication could signal player that pointer inside SlateLoader has reached an end of the list and will repeat patterns starting from the next placement

**Comment by SamsTheNerd** [comment]
I think it's easy enough to just write the list again.
