### ISSUE TITLE
Patterns in text does not work

### ISSUE THREAD

**Issue by aaronhowser1** [SamsTheNerd/HexGloop#8]
![image](https://github.com/SamsTheNerd/HexGloop/assets/15698722/bab8acff-f2db-4200-b4d2-e4fb1d34bdd5)
![image](https://github.com/SamsTheNerd/HexGloop/assets/15698722/babf2973-a0b8-4ec9-b16f-0718da2bee58)
![image](https://github.com/SamsTheNerd/HexGloop/assets/15698722/a75b48d2-0802-4c01-b1a4-04caad8110df)

hexgloop-1.19.2-0.0.4-forge

**Comment by SamsTheNerd** [comment]
seems to be an issue with ftb ranks - i'll patch it soon

**Comment by SamsTheNerd** [comment]
hopefully fixed in v0.1.0

**Comment by WaterWaterovich** [comment]
Hello, I have the same problem, but already at 0.2.0 in forge
![изображение_2024-07-18_215803099](https://github.com/user-attachments/assets/a49cb5eb-10d5-480b-8a8a-b448db7a908a)

**Comment by SamsTheNerd** [comment]
Check if you have mods like emojiful that modify the chat installed
